name: FFA
version: b0.3-b368
main: mc.sseakk.ffa.FFA
authors: [sSeaKk]
description: FFA plugin

commands:
   ffa:
      description: ffa global command
   test:
      description: command for plugin tests