name: FFA
version: a0.3-b24
main: mc.sseakk.ffa.mainpackage.FFA
authors: [sSeaKk]
description: FFA plugin

commands:
   ffa:
      description: ffa global command
   test:
      description: command for plugin tests