name: FFA
version: pa0.1-b55_3
main: mc.sseakk.ffa.mainpackage.FFA
authors: [sSeaKk]
description: FFA plugin (test merge)

commands:
   ffa:
      description: ffa global command
   test:
      description: command for plugin tests